# Generated by Django 4.1.2 on 2022-10-05 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cadastro", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="livro",
            name="titulo",
            field=models.CharField(max_length=200),
        ),
    ]
